colang_version: "1.0"
models: []
instructions: []
rails:
  input:
    flows:
      - financial check input
  output:
    flows:
      - financial check output
  retrieval:
    flows:
      - financial check retrieval
  tool_output:
    flows:
      - tool call validation
  tool_input:
    flows:
      - tool result validation

custom_data:
  financial_guardrails:
    policy_file: ../policies/open_lakera_v1.yml
    mode: enforce
